---


- name: Prepare ansible host
  hosts: 127.0.0.1
  connection: local
  tasks:
  - name: Install sshpass
    yum: name={{item}} state=present
    with_items:
      - sshpass

  - name: Install rsync
    yum: name=rsync state=present

  - name: Install python-pip
    yum: name=python-pip state=present
    when: ansible_os_family == "RedHat" and {{ ansible_distribution_version | version_compare('7.0', '<') }}

  - name: Upgrade Jinja2
    command: pip install Jinja2 --upgrade
    when: ansible_os_family == "RedHat" and {{ ansible_distribution_version | version_compare('7.0', '<') }}

  - name: Copy fixed unarchive module - broken in ansible 2.1.0.0
    copy: src={{ item }} dest=/usr/lib/python2.7/site-packages/ansible/modules/core/files/
    become: true
    with_fileglob:
      - files/ansible/unarchive.*
    when: "{{ ansible_version.full | version_compare('2.0.2.0', '>') }} and {{ ansible_version.full | version_compare('2.1.0.0', '<=') }}"

  # TODO: ADD GIT KEYS ?

  - name: Clone API repository
    git: repo=https://github.com/Medicasoft/{{ target_source }}-dist-app dest=../{{ target_source }}-dist-app update=yes recursive=no

  - name: Clone UI repository
    git: repo=https://github.com/Medicasoft/{{ target_source }}-dist-ui dest=../{{ target_source }}-dist-ui update=no

  - name: Copy couchbase resources for administrator user
    synchronize: src=files/couchbase/data/ dest=../{{ target_source }}-dist-app/database/couchbase/data/