---

- name: Update IP addresses
  hosts: dbmaster
  become: true
  tasks:
    - name: Update pg_hba.conf
      template:
        src: "./roles/postgresql/templates/pg_hba.conf.j2"
        dest: "/var/lib/pgsql/{{postgres_version}}/data/pg_hba.conf"
        owner: "{{postgresql_admin_user}}"
        group: "{{postgresql_admin_user}}"
        mode: 0640

    - name: Restart postgresql
      service: name=postgresql-{{postgres_version}} state=restarted


    # CONF_FILE FIX
    - lineinfile:
        dest=/etc/sysconfig/elasticsearch
        regexp="^CONF_FILE={{ elasticsearch_conf_dir }}/elasticsearch.yml"
        insertafter=EOF
        line="CONF_FILE={{ elasticsearch_conf_dir }}/elasticsearch.yml"

    - name: Configure Elasticsearch Node
      template: src="./roles/elasticsearch/templates/elasticsearch.yml.j2" dest={{ elasticsearch_conf_dir }}/elasticsearch.yml owner={{ elasticsearch_user }} group={{ elasticsearch_group }} mode=0644
      when: elasticsearch_conf_dir is defined and ansible_os_family == "RedHat"

    - name: Restarting Elasticsearch
      service: name=elasticsearch state=restarted